### ISSUE TITLE
Making reservations from admin resources page

### ISSUE THREAD

**Issue by FelixLoether** [City-of-Helsinki/varaamo#499]
Steps to make a reservation:

1. Move mouse to the start time (any available time slot).

    *UI*: The hovered slot is blue.

2. Click on the start time.

    *UI*: Change clicked slot to blue and show a popover above it (content: 'Choose reservation end time.' and '9:00-9:30').

3. Move mouse to the end time. 

    *UI*: The hovered slot and the start time slot are blue, the slots between are light blue. The time in the popover changes as slots are hovered.

4. Click on the end time.

    *UI*: Open a reservation confirmation modal.

5. Click 'Save' button.

    *UI*: Once request has been completed, close reservation modal and add the reservation info to the timeline.

## Part 1 - Selecting time

- [x] Select start time on first click.
  - `shared/availability-view/.../AvailabilityTimeline`
    - [x] Add handleReservationSlotClick function. Call `props.onReservationSlotClick({ resourceId: props.id, ...data })`.
    - [x] Add prop `id`, resource id.
  - `shared/availability-view/.../TimelineGroups`
    - [x] Add prop `onReservationSlotClick`.
    - [x] Pass `onReservationSlotClick={props.onReservationSlotClick}` to TimelineGroup.
  - `shared/availability-view/AvailabilityView`
    - [x] Add initial state: `{ selection: null }`.
    - [x] Add function handleReservationSlotClick. For now only calls `setState({ selection: { begin: ..., resourceId: ... } })`.
    - [x] Pass `onReservationSlotClick={this.handleReservationSlotClick}` to TimelineGroups.
- [x] Select end time on second click.
  - `shared/availability-view/AvailabilityView`
    - [x] Add prop `onSelect`.
    - [x] Modify handleReservationSlotClick. Add `if (this.state.selection) { ... }`:
      - If click data's resourceId is different or the click is before `selection.begin`, do nothing (i.e. prevent the click).
      - If click data's resourceId is the same and the click is the same or after `selection.begin`, update `state.selection.end` and call `this.props.onSelect(selection)` and clear `state.selection`.
- [x] Clear selection start when date changed.
  - Already done because AvailabilityView gets re-rendered when the day changes.

## Part 2 - Making a reservation

- [x] Open modal when end time selected.
  - `pages/admin-resources/AdminResourcesPage`
    - [x] Pass `onSelectionChange={this.handleSelect}` to AvailabilityView.
    - [x] Add function `handleSelect(selection)`.
      - [x] Do `this.setState({ selection })`.
      - [x] Dispatch `ui.openConfirmReservationModal()`.
    - [x] If this.state.selection, render `<ReservationConfirmation params={{ id: selectedResourceId }} selectedResources={[this.state.selection]} />`.
  - [x] Move `pages/resource/reservation-confirmation/` to `shared/reservation-confirmation/`.
- [x] Create reservation when modal 'Save' button clicked.
- [x] Close modal when reservation created.
- [x] Show created reservation in timeline.
- [x] Show "Reservation successful" modal on the correct page (and clear to make sure it's not shown when going to the resource page).

## Part 3 - Highlighting slots

- [x] Highlight start slot.
  - `shared/availability-view/AvailabilityView`
    - [x] Pass `selection={this.state.selection}` to TimelineGroups.
    - [x] Change startSelection to also set selection.end.
  - `shared/availability-view/.../TimelineGroups`
    - [x] Pass `selection={this.props.selection}` to TimelineGroup.
  - `shared/availability-view/.../AvailabilityTimeline`
    - [x] Pass `resourceId={this.props.id}` to ReservationSlot.
  - `shared/availability-view/.../ReservationSlot`
    - [x] Add `&& (!selection.resourceId || selection.resourceId === this.props.resourceId)`.
- [x] Add ReservationSlot.onMouseEnter/Leave.
  - `shared/availability-view/.../ReservationSlot`
    - [x] Add props `onMouseEnter` and `onMouseLeave`.
    - [x] Add functions `handleMouseEnter` and `handleMouseLeave`, call prop with `{ begin, end, resourceId }`.
    - [x] Add onMouseEnter and onMouseLeave to the element.
    - [x] Add resourceId to onClick data.
  - `shared/availability-view/.../AvailabilityTimeline`
    - [x] Remove `handleReservationSlotClick`.
    - [x] Pass `onReservationSlotMouseEnter/Leave` to ReservationSlot.
  - `shared/availability-view/.../AvailabilityTimelineContainer`
    - [x] Add `onReservationSlotMouseEnter/Leave` to prop types.
  - `shared/availability-view/.../TimelineGroup`
    - [x] Pass `onReservationSlotMouseEnter/Leave` to AvailabilityTimelineContainer.
  - `shared/availability-view/.../TimelineGroups`
    - [x] Pass `onReservationSlotMouseEnter/Leave` to TimelineGroup.
- [x] Highlight hovered slot and slots between start slot and hovered slot.
  - `shared/availability-view/AvailabilityView`
    - [x] Add function `handleReservationSlotMouseLeave`.
      - Do `this.setState({ hoverSelection: null })` if `this.state.hoverSelection === selection`.
    - [x] Add function `handleReservationSlotMouseEnter`.
      - Do `this.setState({ hoverSelection: selection })` if `!state.selection || (state.selection.resourceId === selection.resourceId && state.selection.begin < selection.begin)`.
    - [x] When passing selection to TimelineGroups, modify it based on state.hoverSelection.
      - If no state.hoverSelection: use state.selection.
      - If state.hoverSelection and no state.selection, use state.hoverSelection.
      - Otherwise use `{ ...state.selection, end: state.hoverSelection.end }`.
    - [x] Pass `onReservationSlotMouseEnter/Leave` to TimelineGroups.

## Part 4 - Popover information

- [x] Display popover on start slot.
- [x] Display time from start to hovered slot in popover. Display selected time if end time has been selected.

## Part 5 - Prevent invalid selections

- [x] Prevent selections over existing reservations.
