### ISSUE TITLE
Add reservation info modal to availability view

### ISSUE THREAD

**Issue by lraivio** [City-of-Helsinki/varaamo#506]
## Part 1 - Displaying info modal
- [x] Display info modal on availability view
- [x] Only show information that the reservation contains

## Part 2 - commenting, confirming and denying reservations
- [x] Move save comments button directly below comments
- [x] Block commenting past reservations
- [x] Add confirm button
- [x] Add deny button

## Part 3 - cancelling reservations
- [ ] Add cancel button
